### ISSUE TITLE
IMP crashes on Mars.1 (eclipse 4.5.1)

### ISSUE THREAD

**Issue by Ingo60** [impulse-org/imp.runtime#5]
After upgrading to eclipse 4.5.1, the Frege IDE which uses IMP stopped working. (https://github.com/Frege/eclipse-plugin/issues/15).

As far as I understand, the signature of an internal method the IMP is calling was changed slightly, and this causes now a NoMethodFound exception in the initialization of IMP.

Please see this SO post for technical details: http://stackoverflow.com/questions/33111344/eclipse-4-5-1-mars-1-method-not-found-setdefaulteditor

Can we do anything about it? Can we verify the IMP sources compile against the latest eclipse code? And if so, can we deploy an IMP that runs on MARS 4.5.1.

**Comment by PaulKlint** [comment]
Did you try our latest unstable release? This issue has been fixed a week ago.

**Comment by Ingo60** [comment]
No I didn't. Probably, I should, then.

Respect for your foresight!

**Comment by jurgenvinju** [comment]
Hi @Ingo60, we've forked imp.runtime to <https://github.com/usethesource/impulse>; this fork is going to develop more rapidly, so may be more unstable. It runs on Mars.1 and has been stripped of dead code recently. You might switch to it, but it does require a rename in packages and extension point id's. I'd be happy to answer any questions.

The current breakage of imp.runtime can be fixed by a rebuild. Mars.1 has some non-binary compatible API changes w.r.t. Mars. The source code _is_ compatible however, so you can recompile with Mars.1 API bundles using a Java 8 compiler  and it should work again.

**Comment by Ingo60** [comment]
@jurgenvinju I definitly would want to give it a try, but I would certainly need some documentation for migration of the [frege.ide](https:://github.com/Frege/eclipse-plugin). 

To be honest, I have only vague ideas about what an extension point or a bundle is, or how to recompile "with Mars.1 API bundles". This is the very reason I used IMP in the first place, to not get exposed to this stuff. (No offense here - I can see that IDE building is interesting and demanding, and I hold people who do it in very high esteem ... but I have so many very different things to do ...)

**Comment by jurgenvinju** [comment]
@Ingo60 I made a pull request to show what would be needed. Please see the discussion there: Frege/eclipse-plugin/pull/16

**Comment by Ingo60** [comment]
Was able to fix this with using IMPULSE. Runs on LUNA and MARS.1

**Comment by jurgenvinju** [comment]
👍
